### PR TITLE
Content tags

### PR DESCRIPTION
**Pull request by mdo997**
implemented content update method.

### CODE REVIEW

**Comment by carolynrehm** [comment]
1. Open this merge from dev and pull from it.  This was opened from master again, and changing to dev shows a merge conflict.
2. Remove non documentation comments; good code should be self documenting.

**Comment by mdo997** [comment]
@carolynrehm fixed merging conflicts for content-tags, please review. Thank you!

**Comment by carolynrehm** [comment]
This looks good so far, but I would suggest including confirmation for deletion. Prevent mistakes by including a dialogue box confirming user intent.

**Comment by carolynrehm** [comment]
previous comment actually belongs in the frontend pull request

**Comment by carolynrehm** [comment]
These changes look good, though. I just merged in config changes so those will need to be reflected before these changes can be merged. It also might be helpful to add detail to exceptions (like [this one](https://github.com/revaturelabs/cms-content-service/blob/4d0de88184e2da60453e87869846035a4a28bbf1/src/main/java/com/revature/services/ContentServiceImpl.java#L43) ) so that when they're logged they provide more information

**Comment by mdo997** [comment]
@carolynrehm, Backend content-tags conflicts has been resolved and I have implemented better thrown exceptions for better logging.

**Review by carolynrehm — APPROVED** [review]

**Pull request merged**
