### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by mantunguyen**
Logging for Controller and Services

### CODE REVIEW

**Review by carolynrehm — COMMENTED** [review]
I see all of the advice is AfterReturning. Is there anything set up to log if an exception is thrown?

**Comment by carolynrehm** [comment]
I see now that that's been handled with Matt's pull request. I'll review each of them

**Comment by carolynrehm** [comment]
He handles custom exceptions, but what if a different exception is thrown? Will it get logged?

**Comment by DustinMartin95** [comment]
Yes it should get logged, any method with the LogException annotation will have all exceptions logged

**Comment by carolynrehm** [comment]
Where is the LogException annotation being used?

**Comment by DustinMartin95** [comment]
The annotation is above all the methods in the ServiceImpls The implementation of the aspect to handle the error exception logging is in ExceptionAspect class which was created before this sprint

**Comment by carolynrehm** [comment]
Is there any possibility for exceptions before reaching the service layer?

**Comment by DustinMartin95** [comment]
There was one instance I could see that an error could happen in SearchController, will be also looking into the warning suppressing a little now but as far as logging an exception would be logged there now

**Review by carolynrehm — APPROVED** [review]

**Pull request merged**
